# Generated by Django 4.2.7 on 2023-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Friuts', 'Friuts'), ('Candies', 'Candies'), ('Beverages', 'Beverages')], max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
    ]
